// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnzscpscgajjjniktgdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuenNjcHNjZ2FqampuaWt0Z2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MzIyMDIsImV4cCI6MjA0OTMwODIwMn0.ALxlhCbO0YcOLye9R8tFgdtI0MW4ymeSfeOZQVZYWMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);